# Generated by Django 4.0.2 on 2022-06-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_BK',
            fields=[
                ('bk_profil_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bk_nama', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nama')),
                ('bk_nip', models.CharField(blank=True, max_length=120, null=True, verbose_name='NIP')),
                ('bk_nuptk', models.CharField(blank=True, max_length=120, null=True, verbose_name='NUPTK')),
                ('bk_tempat_tanggal_lahir', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tempat, Tanggal Lahir')),
                ('bk_jabatan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Jabatan')),
                ('bk_pangkat_golongan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Pangkat Golongan')),
                ('bk_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profil Bimbingan Konseling',
            },
        ),
    ]
