# Generated by Django 4.0.2 on 2022-06-15 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role_murid', '0002_profil_murid_murid_ekskul'),
        ('role_bk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BK_Catatan',
            fields=[
                ('bk_catatan_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('bk_catatan_status', models.CharField(blank=True, choices=[('Peringatan', 'Peringatan'), ('Himbauan', 'Himbauan'), ('Pengumuman', 'Pengumuman')], max_length=30, null=True, verbose_name='Status')),
                ('bk_catatan', models.TextField(max_length=300, verbose_name='Catatan')),
                ('bk_catatan_siswa', models.ForeignKey(blank=True, help_text='Tidak perlu diisi ketika catatan berstatus pengumuman', null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
            ],
            options={
                'verbose_name_plural': 'Catatan',
            },
        ),
    ]
