# Generated by Django 4.0.2 on 2022-06-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_Pembimbing',
            fields=[
                ('ekskul_profil_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('ekskul_nama', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nama Lengkap')),
                ('ekskul_tempat_tanggal_lahir', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tempat, Tanggal Lahir')),
                ('ekskul_alamat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat')),
                ('ekskul_telp', models.CharField(blank=True, max_length=200, null=True, verbose_name='No Telp / Whatsapp')),
                ('ekskul_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profil Pembimbing',
            },
        ),
    ]
