# Generated by Django 4.0.2 on 2022-06-03 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_skl_jenjang_kelas_skl_jurusan_skl_profil_sekolah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKL_Mata_Pelajaran_Wajib',
            fields=[
                ('mapel_wajib_pelajaran_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Mata Pelajaran')),
                ('mapel_wajib_pelajaran', models.CharField(blank=True, max_length=120, null=True, verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Data Mata Pelajaran Wajib',
            },
        ),
        migrations.AlterModelOptions(
            name='skl_profil_sekolah',
            options={'verbose_name_plural': 'Profil Sekolah'},
        ),
        migrations.CreateModel(
            name='SKL_Mata_Pelajaran_Jurusan',
            fields=[
                ('mapel_jurusan_pelajaran_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Mata Pelajaran')),
                ('mapel_jurusan_pelajaran', models.CharField(blank=True, max_length=120, null=True, verbose_name='Mata Pelajaran')),
                ('mapel_jurusan_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_jurusan', verbose_name='Jurusan')),
            ],
            options={
                'verbose_name_plural': 'Data Mata Pelajaran Jurusan',
            },
        ),
    ]
