# Generated by Django 4.0.2 on 2022-06-03 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_skl_mata_pelajaran_wajib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKL_Semester',
            fields=[
                ('skl_s_semester_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Semester')),
                ('skl_s_semester', models.IntegerField(blank=True, null=True, verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='SKL_Tahun_Ajaran',
            fields=[
                ('skl_t_tahun_ajaran_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Tahun Ajaran')),
                ('skl_t_tahun_ajaran', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tahun Ajaran')),
            ],
        ),
    ]
