# Generated by Django 4.0.2 on 2022-06-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_skl_semester_skl_tahun_ajaran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skl_mata_pelajaran_jurusan',
            options={'verbose_name_plural': 'PL | Data Mata Pelajaran Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='skl_mata_pelajaran_wajib',
            options={'verbose_name_plural': 'PL | Data Mata Pelajaran Wajib'},
        ),
        migrations.AlterModelOptions(
            name='skl_semester',
            options={'verbose_name_plural': 'PL | Semester'},
        ),
        migrations.AlterModelOptions(
            name='skl_tahun_ajaran',
            options={'verbose_name_plural': 'PL | Tahun Ajaran'},
        ),
    ]
