# Generated by Django 4.0.2 on 2022-06-10 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_alter_skl_mata_pelajaran_jurusan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKL_Ekskul',
            fields=[
                ('skl_ekskul_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Ektrakulikuler')),
                ('skl_ekskul', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ektrakulikuler',
            },
        ),
    ]
