# Generated by Django 4.0.2 on 2022-06-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_skl_ekskul'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='is_pembimbing_ekskul',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Role Pembimbing Ekskul'),
        ),
    ]
