# Generated by Django 4.0.2 on 2022-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_akun_is_pembimbing_ekskul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='is_pembimbing_ekskul',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Role Pelatih Ekskul'),
        ),
    ]
