# Generated by Django 4.0.2 on 2022-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_alter_akun_is_pembimbing_ekskul'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='is_kepsek',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Role Kepala Sekolah'),
        ),
    ]
