# Generated by Django 4.0.2 on 2022-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_akun_is_kepsek'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='is_bk',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Role BK'),
        ),
    ]
