# Generated by Django 4.0.2 on 2022-06-03 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0003_skl_mata_pelajaran_wajib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_Guru',
            fields=[
                ('guru_profil_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guru_nama', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nama')),
                ('guru_nip', models.CharField(blank=True, max_length=120, null=True, verbose_name='NIP')),
                ('guru_nuptk', models.CharField(blank=True, max_length=120, null=True, verbose_name='NUPTK')),
                ('guru_tempat_tanggal_lahir', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tempat, Tanggal Lahir')),
                ('guru_jabatan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Jabatan')),
                ('guru_pangkat_golongan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Pangkat Golongan')),
                ('guru_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Pengampu Mata Pelajaran Jurusan')),
                ('guru_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Pengampu Mata Pelajaran Wajib')),
                ('guru_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
