# Generated by Django 4.0.2 on 2022-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_guru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil_guru',
            options={'verbose_name_plural': 'Profil Guru'},
        ),
    ]
