# Generated by Django 4.0.2 on 2022-06-03 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0004_skl_semester_skl_tahun_ajaran'),
        ('role_guru', '0002_alter_profil_guru_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil_Guru',
            new_name='Gu_Profil_Guru',
        ),
    ]
