# Generated by Django 4.0.2 on 2022-06-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_skl_ekskul'),
        ('role_guru', '0004_gu_data_teknik_penilaian_gu_data_kompetensi_dasar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gu_profil_guru',
            name='guru_wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_kelas', verbose_name='Wali Kelas'),
        ),
    ]
