# Generated by Django 4.0.2 on 2022-06-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_skl_ekskul'),
        ('role_guru', '0005_gu_profil_guru_guru_wali_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gu_profil_guru',
            name='guru_wali_kelas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_kelas', verbose_name='Wali Kelas'),
        ),
    ]
