# Generated by Django 4.0.2 on 2022-06-15 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role_murid', '0002_profil_murid_murid_ekskul'),
        ('sekolah', '0010_akun_is_bk'),
        ('role_guru', '0006_alter_gu_profil_guru_guru_wali_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gu_Catatan',
            fields=[
                ('guru_catatan_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guru_catatan_status', models.CharField(blank=True, choices=[('Peringatan', 'Peringatan'), ('Himbauan', 'Himbauan'), ('Pengumuman', 'Pengumuman')], max_length=30, null=True, verbose_name='Status')),
                ('guru_catatan', models.TextField(max_length=300, verbose_name='Catatan')),
                ('guru_catatan_siswa', models.ForeignKey(blank=True, help_text='Tidak perlu diisi ketika catatan berstatus pengumuman', null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid')),
                ('guru_kompetensi_dasar_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Mata Pelajaran Jurusan')),
                ('guru_kompetensi_dasar_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Mata Pelajaran Wajib')),
            ],
            options={
                'verbose_name_plural': 'Catatan',
            },
        ),
    ]
