# Generated by Django 4.0.2 on 2022-06-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_guru', '0007_gu_catatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gu_catatan',
            old_name='guru_kompetensi_dasar_mata_pelajaran_jurusan',
            new_name='guru_catatan_dasar_mata_pelajaran_jurusan',
        ),
        migrations.RenameField(
            model_name='gu_catatan',
            old_name='guru_kompetensi_dasar_mata_pelajaran_wajib',
            new_name='guru_catatan_dasar_mata_pelajaran_wajib',
        ),
    ]
