# Generated by Django 4.0.2 on 2022-06-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_guru', '0008_rename_guru_kompetensi_dasar_mata_pelajaran_jurusan_gu_catatan_guru_catatan_dasar_mata_pelajaran_jur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gu_catatan',
            old_name='guru_catatan_dasar_mata_pelajaran_jurusan',
            new_name='guru_catatan_mata_pelajaran_jurusan',
        ),
        migrations.RenameField(
            model_name='gu_catatan',
            old_name='guru_catatan_dasar_mata_pelajaran_wajib',
            new_name='guru_catatan_mata_pelajaran_wajib',
        ),
    ]
