# Generated by Django 4.0.2 on 2022-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_mo_sikap_spiritual_mo_sikap_sosial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mo_sikap_spiritual',
            options={'verbose_name_plural': 'Nilai Sikap Spiritual'},
        ),
        migrations.AddField(
            model_name='mo_sikap_sosial',
            name='mo_proyeksi_nilai',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Proyeksi Nilai ke Angka'),
        ),
        migrations.AddField(
            model_name='mo_sikap_spiritual',
            name='mo_proyeksi_nilai',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Proyeksi Nilai ke Angka'),
        ),
        migrations.AlterField(
            model_name='mo_sikap_sosial',
            name='mo_nilai',
            field=models.CharField(blank=True, choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20, null=True, verbose_name='Nilai'),
        ),
        migrations.AlterField(
            model_name='mo_sikap_spiritual',
            name='mo_nilai',
            field=models.CharField(blank=True, choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20, null=True, verbose_name='Nilai'),
        ),
    ]
