# Generated by Django 4.0.2 on 2022-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role_murid', '0001_initial'),
        ('sekolah', '0006_skl_ekskul'),
        ('monitoring', '0003_alter_mo_sikap_spiritual_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo_penilaian_pengetahuan',
            name='mo_kelas',
            field=models.ForeignKey(blank=True, help_text='Tidak perlu diisi', null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas'),
        ),
        migrations.CreateModel(
            name='Mo_Penilaian_Ekskul',
            fields=[
                ('mo_penilaian_ekskul_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Penilaian Sikap Spiritual')),
                ('mo_nilai', models.FloatField(blank=True, default=None, null=True, verbose_name='Nilai')),
                ('mo_ekskul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_ekskul', verbose_name='Ekstrakulikuler')),
                ('mo_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas')),
                ('mo_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_semester', verbose_name='Semester')),
                ('mo_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
                ('mo_tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_tahun_ajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai Ekstrakulikuler',
            },
        ),
    ]
