# Generated by Django 4.0.2 on 2022-06-10 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_mo_penilaian_pengetahuan_mo_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo_penilaian_ekskul',
            name='mo_penilaian_ekskul_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Penilaian Penilaian Ekstrakulikuler'),
        ),
    ]
