# Generated by Django 4.0.2 on 2022-06-14 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role_murid', '0002_profil_murid_murid_ekskul'),
        ('sekolah', '0009_akun_is_kepsek'),
        ('monitoring', '0005_alter_mo_penilaian_ekskul_mo_penilaian_ekskul_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo_Juara_Ekskul',
            fields=[
                ('mo_juara_ekskul_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Juara Ekstrakulikuler')),
                ('mo_tahun', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tahun Kejuaraan')),
                ('mo_tingkatan', models.CharField(blank=True, choices=[('Sekolah', 'Sekolah'), ('Kota / Kabupaten', 'Kota / Kabupaten'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=120, null=True, verbose_name='Tingkat Kejuaraan')),
                ('mo_pelaksana', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dilaksanakan Oleh')),
                ('mo_kejuaraan', models.TextField(blank=True, max_length=300, null=True, verbose_name='Kejuaraan')),
                ('mo_juara', models.CharField(blank=True, choices=[('I', 'Satu'), ('II', 'Dua'), ('III', 'Tiga'), ('IV', 'Harapan I'), ('V', 'Harapan II'), ('VI', 'Harapan III')], max_length=120, null=True, verbose_name='Juara')),
                ('mo_ekskul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_ekskul', verbose_name='Ekstrakulikuler')),
                ('mo_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
            ],
        ),
    ]
