# Generated by Django 4.0.2 on 2022-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_mo_juara_ekskul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mo_juara_ekskul',
            options={'verbose_name_plural': 'Kejuaraan Ekstrakulikuler'},
        ),
    ]
