# Generated by Django 4.0.2 on 2022-06-15 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_akun_is_bk'),
        ('role_murid', '0002_profil_murid_murid_ekskul'),
        ('role_guru', '0006_alter_gu_profil_guru_guru_wali_kelas'),
        ('monitoring', '0007_alter_mo_juara_ekskul_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo_Penilaian_Ulangan_KKM',
            fields=[
                ('mo_penilaian_kkm_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID KKM')),
                ('mo_kkm', models.FloatField(blank=True, default=0, null=True, verbose_name='KKM')),
                ('mo_jenjang_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.skl_jenjang_kelas', verbose_name='Jenjang Kelas')),
                ('mo_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Mata Pelajaran Jurusan')),
                ('mo_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Mata Pelajaran Wajib')),
            ],
            options={
                'verbose_name_plural': 'KKM',
            },
        ),
        migrations.AlterField(
            model_name='mo_penilaian_ekskul',
            name='mo_nilai',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_keterampilan',
            name='mo_portofolio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Portofolio'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_keterampilan',
            name='mo_praktek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Praktek'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_keterampilan',
            name='mo_produk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_keterampilan',
            name='mo_proyek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Proyek'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_pengetahuan',
            name='mo_nilai_P1_TGS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai P1 TGS'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_pengetahuan',
            name='mo_nilai_P2_TLS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai P2 TLS'),
        ),
        migrations.AlterField(
            model_name='mo_penilaian_pengetahuan',
            name='mo_nilai_P3_TLS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai P3 TLS'),
        ),
        migrations.CreateModel(
            name='Mo_Penilaian_UTS',
            fields=[
                ('mo_penilaian_uts_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Penilaian UTS')),
                ('mo_status', models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Remedial', 'Remedial')], max_length=20, null=True, verbose_name='Status Ulangan')),
                ('mo_nilai', models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai')),
                ('mo_ketuntasan', models.CharField(blank=True, choices=[('Tuntas', 'Tuntas'), ('Belum Tuntas', 'Belum Tuntas')], max_length=20, null=True, verbose_name='Status Ketuntasan')),
                ('mo_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas')),
                ('mo_kkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.mo_penilaian_ulangan_kkm', verbose_name='KKM')),
                ('mo_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Mata Pelajaran Jurusan')),
                ('mo_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Mata Pelajaran Wajib')),
                ('mo_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_semester', verbose_name='Semester')),
                ('mo_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
                ('mo_tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_tahun_ajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai Ulangan Tengah Semester',
            },
        ),
        migrations.CreateModel(
            name='Mo_Penilaian_Ulangan',
            fields=[
                ('mo_penilaian_ulangan_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Penilaian Ulangan')),
                ('mo_status', models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Remedial', 'Remedial')], max_length=20, null=True, verbose_name='Status Ulangan')),
                ('mo_ulangan_ke', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], max_length=20, null=True, verbose_name='Ulangan Ke')),
                ('mo_nilai', models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai')),
                ('mo_ketuntasan', models.CharField(blank=True, choices=[('Tuntas', 'Tuntas'), ('Belum Tuntas', 'Belum Tuntas')], max_length=20, null=True, verbose_name='Status Ketuntasan')),
                ('mo_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas')),
                ('mo_kkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.mo_penilaian_ulangan_kkm', verbose_name='KKM')),
                ('mo_kompetensi_dasar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_guru.gu_data_kompetensi_dasar', verbose_name='Kompetensi Dasar')),
                ('mo_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Mata Pelajaran Jurusan')),
                ('mo_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Mata Pelajaran Wajib')),
                ('mo_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_semester', verbose_name='Semester')),
                ('mo_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
                ('mo_tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_tahun_ajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai Ulangan',
            },
        ),
        migrations.CreateModel(
            name='Mo_Penilaian_UAS',
            fields=[
                ('mo_penilaian_uas_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID Penilaian UAS')),
                ('mo_status', models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Remedial', 'Remedial')], max_length=20, null=True, verbose_name='Status Ulangan')),
                ('mo_nilai', models.FloatField(blank=True, default=0, null=True, verbose_name='Nilai')),
                ('mo_ketuntasan', models.CharField(blank=True, choices=[('Tuntas', 'Tuntas'), ('Belum Tuntas', 'Belum Tuntas')], max_length=20, null=True, verbose_name='Status Ketuntasan')),
                ('mo_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas')),
                ('mo_kkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.mo_penilaian_ulangan_kkm', verbose_name='KKM')),
                ('mo_mata_pelajaran_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_jurusan', verbose_name='Mata Pelajaran Jurusan')),
                ('mo_mata_pelajaran_wajib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_mata_pelajaran_wajib', verbose_name='Mata Pelajaran Wajib')),
                ('mo_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_semester', verbose_name='Semester')),
                ('mo_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role_murid.profil_murid', verbose_name='Siswa')),
                ('mo_tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_tahun_ajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai Ulangan Akhir Semester',
            },
        ),
    ]
