# Generated by Django 4.0.2 on 2022-06-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0004_skl_semester_skl_tahun_ajaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_Murid',
            fields=[
                ('murid_profil_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Profil Murid')),
                ('murid_nama', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nama')),
                ('murid_nisn', models.CharField(blank=True, max_length=120, null=True, verbose_name='NISN')),
                ('murid_nss', models.CharField(blank=True, max_length=120, null=True, verbose_name='NSS')),
                ('murid_npsn', models.CharField(blank=True, max_length=120, null=True, verbose_name='NPSN')),
                ('murid_nomor_induk', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nomor Induk')),
                ('murid_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_kelas', verbose_name='Kelas')),
                ('murid_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_semester', verbose_name='Semester')),
                ('murid_tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.skl_tahun_ajaran', verbose_name='Tahun Ajaran')),
                ('murid_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profil Murid',
            },
        ),
    ]
